CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN');
CREATE TYPE "QuoteStatus" AS ENUM ('DRAFT', 'SENT', 'APPROVED', 'REJECTED', 'CANCELLED');
CREATE TYPE "ContractStatus" AS ENUM ('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED');
CREATE TYPE "FinanceType" AS ENUM ('INCOME', 'EXPENSE');
CREATE TYPE "FileType" AS ENUM ('IMAGE', 'PDF', 'DOCUMENT');

CREATE TABLE "users" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT, "googleId" TEXT, "role" "Role" NOT NULL DEFAULT 'USER', "isActive" BOOLEAN NOT NULL DEFAULT true, "refreshToken" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
CREATE TABLE "profiles" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "full_name" TEXT NOT NULL, "company_name" TEXT, "cpf_cnpj" TEXT, "phone" TEXT, "avatar_url" TEXT, "logo_url" TEXT, "address" TEXT, "city" TEXT, "state" TEXT, "zip_code" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "profiles_pkey" PRIMARY KEY ("id"));
CREATE TABLE "clients" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "name" TEXT NOT NULL, "company_name" TEXT, "email" TEXT, "phone" TEXT, "cpf_cnpj" TEXT, "address" TEXT, "notes" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "clients_pkey" PRIMARY KEY ("id"));
CREATE TABLE "quotes" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "client_id" TEXT NOT NULL, "code_number" TEXT NOT NULL, "status" "QuoteStatus" NOT NULL DEFAULT 'DRAFT', "subtotal" DECIMAL(14,2) NOT NULL DEFAULT 0, "discount" DECIMAL(14,2) NOT NULL DEFAULT 0, "total" DECIMAL(14,2) NOT NULL DEFAULT 0, "notes" TEXT, "valid_until" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "quotes_pkey" PRIMARY KEY ("id"));
CREATE TABLE "quote_items" ("id" TEXT NOT NULL, "quote_id" TEXT NOT NULL, "description" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "unit_price" DECIMAL(14,2) NOT NULL, "total_price" DECIMAL(14,2) NOT NULL, CONSTRAINT "quote_items_pkey" PRIMARY KEY ("id"));
CREATE TABLE "contracts" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "client_id" TEXT NOT NULL, "title" TEXT NOT NULL, "content" TEXT NOT NULL, "value" DECIMAL(14,2) NOT NULL DEFAULT 0, "status" "ContractStatus" NOT NULL DEFAULT 'DRAFT', "start_date" TIMESTAMP(3), "end_date" TIMESTAMP(3), "pdf_url" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "contracts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "categories" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "name" TEXT NOT NULL, "type" "FinanceType" NOT NULL, "color_hex" TEXT DEFAULT '#4F46E5', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "categories_pkey" PRIMARY KEY ("id"));
CREATE TABLE "finance_entries" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "category_id" TEXT, "description" TEXT NOT NULL, "amount" DECIMAL(14,2) NOT NULL, "type" "FinanceType" NOT NULL, "entry_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "notes" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "finance_entries_pkey" PRIMARY KEY ("id"));
CREATE TABLE "notifications" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "is_read" BOOLEAN NOT NULL DEFAULT false, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "notifications_pkey" PRIMARY KEY ("id"));
CREATE TABLE "files" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "filename" TEXT NOT NULL, "file_url" TEXT NOT NULL, "file_type" "FileType" NOT NULL DEFAULT 'DOCUMENT', "size_bytes" INTEGER NOT NULL DEFAULT 0, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "files_pkey" PRIMARY KEY ("id"));
CREATE TABLE "settings" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "theme_mode" TEXT NOT NULL DEFAULT 'system', "language" TEXT NOT NULL DEFAULT 'pt-BR', "email_notify" BOOLEAN NOT NULL DEFAULT true, "ai_provider" TEXT NOT NULL DEFAULT 'mock', "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "settings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "audit_logs" ("id" TEXT NOT NULL, "user_id" TEXT, "action" TEXT NOT NULL, "resource" TEXT NOT NULL, "ip_address" TEXT, "metadata" JSONB, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_googleId_key" ON "users"("googleId");
CREATE UNIQUE INDEX "profiles_user_id_key" ON "profiles"("user_id");
CREATE INDEX "clients_user_id_idx" ON "clients"("user_id");
CREATE INDEX "clients_name_idx" ON "clients"("name");
CREATE INDEX "quotes_user_id_idx" ON "quotes"("user_id");
CREATE INDEX "quotes_client_id_idx" ON "quotes"("client_id");
CREATE UNIQUE INDEX "quotes_user_id_code_number_key" ON "quotes"("user_id", "code_number");
CREATE INDEX "contracts_user_id_idx" ON "contracts"("user_id");
CREATE INDEX "contracts_client_id_idx" ON "contracts"("client_id");
CREATE UNIQUE INDEX "categories_user_id_name_type_key" ON "categories"("user_id", "name", "type");
CREATE INDEX "finance_entries_user_id_idx" ON "finance_entries"("user_id");
CREATE INDEX "finance_entries_user_id_entry_date_idx" ON "finance_entries"("user_id", "entry_date");
CREATE INDEX "notifications_user_id_idx" ON "notifications"("user_id");
CREATE UNIQUE INDEX "settings_user_id_key" ON "settings"("user_id");
CREATE INDEX "audit_logs_user_id_idx" ON "audit_logs"("user_id");

ALTER TABLE "profiles" ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "clients" ADD CONSTRAINT "clients_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "quote_items" ADD CONSTRAINT "quote_items_quote_id_fkey" FOREIGN KEY ("quote_id") REFERENCES "quotes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "categories" ADD CONSTRAINT "categories_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "finance_entries" ADD CONSTRAINT "finance_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "finance_entries" ADD CONSTRAINT "finance_entries_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "files" ADD CONSTRAINT "files_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "settings" ADD CONSTRAINT "settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
